/* Generated By:JavaCC: Do not edit this line. FormulaEvaluatorConstants.java */
package br.cefetrj.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaEvaluatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EIGENVALUE_IDENTIFIER = 4;
  /** RegularExpression Id. */
  int INT_CONST = 5;
  /** RegularExpression Id. */
  int DBL_CONST = 6;
  /** RegularExpression Id. */
  int EXPONENT = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int EOL = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int POWER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<EIGENVALUE_IDENTIFIER>",
    "<INT_CONST>",
    "<DBL_CONST>",
    "<EXPONENT>",
    "<DIGITS>",
    "<DIGIT>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\frac{\"",
    "\"}\"",
    "\"{\"",
    "\"(\"",
    "\")\"",
  };

}
